### ISSUE TITLE
Position error

### ISSUE THREAD

**Issue by Robert-Ven** [uwgraphics/relaxed_ik_ros2#1]
Hi,

I'm using RangedIK on ROS humble (which gives no erros). I'm using it with a UR5e manipulator, so I'm using your ur5 configuration. 

I made a small change in the `relaxed_ik_rust.py` script to be able to publish Float64MultiArray. 

My issue lies in the resulting pose, which has a quite large offset in the Y and Z (relative to `base_link`). Offset along Y is 0.04 m and the offset along Z is 0.07 m. It is very consistent, when moving the arm this stays true, also in different orientation.  

Do you know where the issue might lie?

**Comment by Robert-Ven** [comment]
I updated the URDF to use the one published under /robot_description when using the UR ros2 driver. This solves the issue.

**Comment by yepw** [comment]
Thanks for the note. I didn't know that ur5 and ur5e have different kinematics. I added ur5e's urdf in [relaxed_ik_core](https://github.com/uwgraphics/relaxed_ik_core/).
